### ISSUE TITLE
Quiet mode

### ISSUE THREAD

**Issue by ChristianMoesl** [cksystemsteaching/selfie#103]
Implement a "quiet mode" of the grader, where only the actual grade gets printed on the console. This mode should be activated with a command line option.

**Comment by ckirsch** [comment]
@ChristianMoesl Can you give this priority? I could use the feature for grading this week's assignment already. Thanks!

**Comment by ChristianMoesl** [comment]
@ckirsch it's actually already finished on the grader branch. I marked the commit with (closes #103), s.t. this issue is closed automatically, as soon as the grader branch is merged into the master branch.
