### ISSUE TITLE
Add a new test for Bitwise AND/OR/NOT

### ISSUE THREAD

**Issue by ChristianMoesl** [cksystemsteaching/selfie#104]
Bitwise AND/OR operators should be added to the C* language and emulator support for the corresponding RISC-V instruction should be provided. 

This test should verify:
- the parser correctly decides, if a  is in C* or not. 
- the precedence of the operator is implemented like in C
- the generated instructions have the correct RISC-V encoding
- the semantics of the instruction is correctly implemented in the emulator

**Comment by ckirsch** [comment]
Let's include bitwise NOT (`~`) as well. Its precedence is interesting.

**Comment by ckirsch** [comment]
`~` should be mapped to `XORI` RISC-V.

**Comment by ChristianMoesl** [comment]
Ok, I am on it. 👍

**Comment by ckirsch** [comment]
Thanks! This is a cool assignment. It challenges the students to take what they learned for bitwise shifting one step further.
