### ISSUE TITLE
Basic Tests

### ISSUE THREAD

**Issue by ChristianMoesl** [cksystemsteaching/selfie#105]
Add a set of basic tests, which should run on every invocation and have to succeed, to get a grade < 5. 

This tests should basically check: 
- if selfie is compilable with gcc (check for `exit-status == 0`)
- if selfie compiles itself without warnings

**Comment by ChristianMoesl** [comment]
@ckirsch I am not sure, if my requirements written above, matches that, what you want from me. The way i understood you, you wanted me to check for warnings, when `selfie.c` get's compiled with `gcc` or `clang`. But I think, this might not be a good idea, since we enable with `-Wall -Wextra` a wide range of warnings, which are highly dependent on the compiler and the compiler version.

Currently it's implemented, like I wrote it down above.

**Comment by ckirsch** [comment]
I am not sure I understand what exactly you test for now. Can you explain?

**Comment by ChristianMoesl** [comment]
I test two things:

1. If `make clean && make selfie` results in `exit_code == 0`
2. If `./selfie -c selfie.c` results in `exit_code == 0` and there is no `warning`or `syntax error` printed
