### ISSUE TITLE
Create Readme file

### ISSUE THREAD

**Issue by ChristianMoesl** [cksystemsteaching/selfie#114]
A Readme file (in `grader/`) should be written to document the self-grader.

**Comment by Blazefrost** [comment]
There is a README in the grader directory which evolved from the HOWTO guide and the assignment workflow guide. I think it does a good job on describing the grader's usage and assignment workflows. 

We could add a reference to the assignment descriptions in the 'assignments/' directory, though.

**Comment by ckirsch** [comment]
@Blazefrost Good idea! Please add that reference. Thanks!
