### ISSUE TITLE
Second and third argument of `-se` option should be optional

### ISSUE THREAD

**Issue by ckirsch** [cksystemsteaching/selfie#154]
@ChrisEdel The `-se` option requires at least two arguments. This is inconsistent with the usage pattern printed by selfie and the readme explaining the option. I suggest to make the second argument optional similar to the third argument (`--merge-enabled`) and still ignore the second and third argument in the usage pattern and readme. Can you please fix that through a PR?

**Comment by ChrisEdel** [comment]
Sure, I will take care of that.

**Comment by ChrisEdel** [comment]
I have created the PR. However, the travis check failed due to some docker issue with the grader (`The command "docker run cksystemsteaching/selfie make grader" exited with 2.`).
