### ISSUE TITLE
smalloc: possible array out-of-bound access when out of memory in init_library

### ISSUE THREAD

**Issue by maroneze** [cksystemsteaching/selfie#158]
When running a code analysis with [Frama-C](https://github.com/Frama-C/Frama-C-snapshot) on selfie, I got the following alarms:

```
file        function                kind           alarm
----------------------------------------------------------------------------------------
selfie.c    two_to_the_power_of     mem_access      \valid_read(power_of_two_table + p)
selfie.c    two_to_the_power_of     initialization  \initialized(power_of_two_table + p)

stack: two_to_the_power_of <- get_bits <- load_character <- 
  print_format1 <- printf1 <- smalloc <- init_library <- main
```

What they mean is that, in case the call to `smalloc` fails (due to lack of memory) *while initializing the library*, because we didn't have time to properly allocate and initialize the global pointer `power_of_two_table`, the error message from `smalloc` itself may trigger a null pointer dereferencing.

In practice, this is extremely unlikely to happen; but in case there is some pedagogical interest in such corner cases, I'm reporting it here. One way to avoid it might be to test that `power_of_two_table` is not null before trying to print anything, for instance.

Please feel free to close this issue if you find it nitpicky.

**Comment by ckirsch** [comment]
@maroneze Thanks a lot for pointing this out. The issue indeed has educational value. @ChristianMoesl did smalloc and will look into a fix. @ChristianMoesl I think, it is best to exit if initialization does not go through.

**Comment by maroneze** [comment]
For completeness, the same thing might happen with `character_buffer` (print <- print_format1 <- printf1 called if the first smalloc() fails); exiting early should avoid both issues.

**Comment by ChristianMoesl** [comment]
`write()` could also be used for this error message. However, `selfie_name` could not be printed in this case and the printed error message would have to be double-word aligned.

**Comment by ckirsch** [comment]
@maroneze If you are interested in doing that please feel free to submit a PR. Keep in mind though that we need simple, educational code to be able to pull any PR. Many thanks!

**Comment by maroneze** [comment]
I proposed a PR, but not sure it is good enough, so feel free to dismiss it if you wish.

On the same kind of warnings, I have a few other issues with my analysis, mostly due to mismatches between the strict C semantics and the hardware model; for instance, when comparing strings such as `"-c"` (during argument parsing), the code in `load_character`, namely `*((uint64_t*) s + a)`, implicitly assumes that the string `s` has at least 8 bytes, otherwise the memory access is invalid. This is more of a portability issue, and I don't have any suggestions other than padding the string with `\0`s (possibly with some macro).

And finally, function `touch` dereferences uninitialized memory (just after calling `smalloc`) using a type other than `char`, which in theory could trigger some trap representation and cause undefined behavior. Once again, this is more on the theoretical side, and probably not a real issue.

I'll try to identify some more "concerning" issues in the future and report them if I find anything. Just reported these here in case some zealous C language lawyer might wonder about them.
