### ISSUE TITLE
atoi() unreliable overflow handling

### ISSUE THREAD

**Issue by HugoPlatzer** [cksystemsteaching/selfie#16]
# Description of problem
the atoi() function does not always fail when an integer literal representing a number larger than 2^31 is processed.

# Example

`int main() {
    int a;
    a = 9999999999;
    return 0;
}`

compiles successfully while

`int main() {
    int a;
    a = 2222222222;
    return 0;
}`

doesn't.

# Cause

Multiplying , for example, 999999999 with 10 , as done at the end of the conversion for "9999999999" obviously causes an overflow. The resulting int value is however positive so the check `n < 0` does not trigger.

# Possible fix

Check for overflows in a different way: Store a value `x = INT_MAX  / 10 = 214748364` and a maximum digit `y = 8`. Before introducing a new digit c to the number n, fail if

1.  `n > x or (n == x and c > y)`, this is true if and only if `n * 10 + c` mathematically is larger than INT_MAX + 1, so the input string represents a number larger than abs(INT_MIN).

2. `n == INT_MIN`, since there are digits remaining, the input string represents too large a number.

See [this commit](https://github.com/cksystemsteaching/cc-2017-HugoPlatzer/commit/d1e494ee63a55e12d20970d6f763ad95500a54d1) for code (no pull request possible because of private repo).

**Comment by ckirsch** [comment]
@HugoPlatzer Interesting! Can you do this in a way that `atoi` never produces an integer overflow, even when scanning INT-MIN? I'd like to remove all overflows from the code and this is a good opportunity. Feel free to fork `selfie` publicly and do your PR from there.

**Comment by ckirsch** [comment]
@HugoPlatzer I just saw this again. Very nice! Without remembering your solution I came up with the same yesterday, see https://github.com/cksystemsteaching/selfie/pull/28
