### ISSUE TITLE
Add a reference to assignment descriptions to the grader

### ISSUE THREAD

**Issue by Blazefrost** [cksystemsteaching/selfie#189]
@aemonk summarized all assignment descriptions from the cc2020 slack channel into a Markdown file as a quick reference. In the grader, we could add references back to the descriptions of each assignment so that the aim of each assignment is easier to understand.

Reference: https://cksystemsteaching.slack.com/archives/CUQUKPD61/p1598390644002700

**Comment by Blazefrost** [comment]
One question that we may need to discuss is how the link to the document should be made. The way I see it, there are two possible ways:

- **Head of `master`**: The description link points to the newest commit pushed to a specific branch. If we change the description of an assignment, we don't necessarily have to update the link in the grader to point to the newest version.
  (e.g. https://github.com/cksystemsteaching/selfie/blob/grader/grader/compiler-assignments.md#assignment-0)
- **Specific commit**: The description link points to a specific commit. If new changes are pushed to any branch on the repository, the link to the description will still point to the same version as before. This approach requires manual adjustment even if we just refine the description, but makes the history more understandable, e.g. if we introduced a lot of changes to an assignment, older commits with the old assignment version would still point to an older version of the assignment description instead of the newer, potentially incompatible one.
  (e.g. https://github.com/cksystemsteaching/selfie/blob/9073bc2c49f688b9ff14a3332fed5787f594dd34/grader/compiler-assignments.md#assignment-0)

**Comment by ckirsch** [comment]
I recommend to do head of master but not number the assignments. Just use names. Is that possible?

**Comment by Blazefrost** [comment]
GitHub automatically creates IDs corresponding to the heading. We could try to explicitly add another ID, as suggested by [this StackOverflow answer](https://stackoverflow.com/a/7335839). If this did not work, we would need to edit the heading itself.

**Comment by ckirsch** [comment]
Ok!
