### ISSUE TITLE
Description of Introductory Assignments

### ISSUE THREAD

**Issue by aemonk** [cksystemsteaching/selfie#199]
I worked out some exercises for the introductory assignments, especially at [Architecture](https://github.com/cksystemsteaching/selfie/blob/grader/grader/introductory-assignments.md#2-architecture).

@Blazefrost and I talked about different exercise styles. Currently, I am writing on another version where I describe more than just the exercises. @ckirsch would that be better, or is it enough to link to resources?

We thought that we should save time and concentrate more on the coding exercises.

**Comment by ckirsch** [comment]
@aemonk Exercises that we can use in the upcoming class have highest priority. Think of producing material that I can use in class right away. When writing about numbers use correct prefixes: 0b1010 for binary, 0x1010 for hexadecimal, 0o1010 for octal. Remove the $ signs. They are confusing.

**Comment by ckirsch** [comment]
Try to write up self-contained exercises where the provided information is sufficient and necessary, not more, not less.

**Comment by ckirsch** [comment]
Think of a good sequence of introductory assignments at the beginning of the class. Remove all planned stuff from introductory-assignments.md Instead make that file self-contained so that I can point the students to it.

**Comment by ckirsch** [comment]
Create a GitHub project in the selfie repo to keep track of what you plan to do. @ChristianMoesl can help you with that. All files in the selfie repo should be ready for use. I will keep merging your changes in the grader branch into the master branch for the students to look at.

**Comment by aemonk** [comment]
> Think of a good sequence of introductory assignments at the beginning of the class. Remove all planned stuff from introductory-assignments.md Instead make that file self-contained so that I can point the students to it.

Removed all planned stuff from the file and made a new first version of how it could work.
I referenced all the material to the selfie manuscript (book), everything is beautifully described there. 

@ckirsch please let me know what you think about this style.

**Comment by ckirsch** [comment]
Version 2 is better. But don't mix low- and high-level questions. Creating semantics is very high-level and difficult to answer.

**Comment by ckirsch** [comment]
I recommend to focus on low-level questions for now.
