### ISSUE TITLE
Syllabus for iOS

### ISSUE THREAD

**Issue by aemonk** [cksystemsteaching/selfie#200]
Write a syllabus for iOS and add any missing content.

**Comment by aemonk** [comment]
In WS19 we had 11 events that took place, I have written down the contents here.
According to the calendar, there are 16 events planned for WS20, so we would run out of 5 more or should we split them up?

# Syllabus

- Introduction
	- Bit, nibble, byte
	- Binary, Decimal, unary, octal, hexadecimal
	- How many bits in 6 GB
	- Computation
	- Software
- Architecture 17.10
	- binary vs. decimal
	- Time & space
	- von Neumann Architecture
		- CPU
		- Main memory
	- Code vs. data
	- Software
	- Memory bus
- Architecture 2 24.10
	- von Neumann Architecture
	- Meaning
	- ASCII
	- Byte addressed & word aligned
	- Dataflow (add instruction)
	- fetch, decode, execute
- Tools
	- GHz
	- single & dualcore
	- RAM, storage, network, program, process
	- Time, space, energy
	- Throughput, Latency
- RISC-U & ISA
	- unicast, multicast, broadcast
	- open protocol, open source, open hardware
	- RISCU, ISA
	- Load, store instructions explained
	- Syntax, data flow, control flow
	- Signed, unsigned integer
	- Binary arithmetics
	- Program counter
	- Compiler
- Programming Languages
	- Imperatie, functional, logical
	- Difference between syntax and semantics
	- Notation
		- Multi- and singleline comments
		- Variable decleration
		- Function definition
		- Variable definition
		- Writing the "Hello World" function
	- Compilation, interpretation
- Semantics
	- Global & local variables
	- Procedures, assignment
	- Binary & unary operator (pointer)
	- Memory model
	- EBNF grammar
- Finite State Machine
	- Introduction to FSM
	- Regular Expressions, Scanner
	- PDA, push, pop, stack
- Pushdown Automata
	- Context free grammar
	- Parser, EBNF
	- FSM, `get_symbol()`
	- RISC-U, create meaning
		- Compiler
		- Interpreter
		- Virtualization
- Virtual Memory
	- Whole state of the machine, spatial locality
	- Storage & address space
	- Page, page table (calculation)
- Virtualization
	- Fetch, decode, execute
	- RISC-U instructions
	- State space
	- Virtualization
		- Emulation
		- Virtualization 
	- Context switching
	- Scheduling
		- Cooperative
		- preamptive
	- Hypervisor

**Comment by aemonk** [comment]
I only want to deal with the contents that will be part of the lecture.
Please give me some feedback if this list fits or if we should add something to it? @ckirsch

**Comment by ckirsch** [comment]
@aemonk looks good!
