### ISSUE TITLE
2) Architecture - Introductory Assignments

### ISSUE THREAD

**Issue by aemonk** [cksystemsteaching/selfie#202]
- [x] binary vs. decimal
- [x] von Neumann Architecture
- [x] CPU
- [x] Main memory
- [x] Memory bus
- [x] Code vs. data

**Comment by aemonk** [comment]
**2) Architecture**
Content for Binary vs Decimal in the first version is done. 

I will finish each content one by one and then upload it to make it easier to correct. 
For future topics, I will surely come back to you more often @Blazefrost

**Comment by aemonk** [comment]
Version 1 of von Neumann Architecture finished.

**Comment by aemonk** [comment]
I was able to finish most of the content for architecture-1. 
The only thing missing is the memory-bus, which I still have one or two questions. 
I wanted to ask you to read about what I have written so far. Thanks. @ckirsch @Blazefrost

**Comment by ckirsch** [comment]
@aemonk Looks great! There are just a few typos.

**Comment by aemonk** [comment]
> @aemonk Looks great! There are just a few typos.

Should I rewrite something?

**Comment by ckirsch** [comment]
No, just fix the typos.

**Comment by aemonk** [comment]
I did a spell check and hopefully fixed all typos.
