### ISSUE TITLE
3) Architecture 2 - Introductory Assignments

### ISSUE THREAD

**Issue by aemonk** [cksystemsteaching/selfie#203]
- [x] signed and unsigned integer (moved under 1-Introduction)
- [x] binary arithmetics
- [x] Arithmetic overflow
- [x] Unicode

**Comment by aemonk** [comment]
Added the topic "signed and unsigned integers", could you please check if it meets your requirements? @ckirsch

**Comment by ckirsch** [comment]
@aemonk Looks very nice. I only suggest to move the material on integers to the first section as part of encoding numbers.
