### ISSUE TITLE
Clean up gcc/clang toolchain in Dockerselfie image to support 32-bit and 64-bit x86 and RISC-V

### ISSUE THREAD

**Issue by ckirsch** [cksystemsteaching/selfie#228]

**Comment by ckirsch** [comment]
@Blazefrost Here's what I get after installing `libc6-dev-i386` in the Dockerselfie image:

cc -Wall -Wextra -O3 -m32 -D'uint64_t=unsigned long' selfie.c -o selfie
selfie.c:102:7: warning: mismatch in argument 1 type of built-in function 'malloc'; expected 'unsigned int' [-Wbuiltin-declaration-mismatch]
  102 | void* malloc(unsigned long);
      |       ^~~~~~
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/9/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/9/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
collect2: error: ld returned 1 exit status

**Comment by ckirsch** [comment]
We may need to think about a more systematic way of building our toolchain...the Dockerselfie file should contain comments as to why certain items are needed.

**Comment by Blazefrost** [comment]
`libc6-dev-i386` did work with clang. For gcc, I successfully tested it with `gcc-multilib` and `libgcc-10-dev-i386-cross`, but it seems `gcc-multilib` causes the removal of `gcc-riscv64-linux-gnu` which is rather subobtimal

**Comment by Blazefrost** [comment]
It seems like `lib32gcc-9-dev` and `libc6-dev-i386-amd64-cross` will suffice, too. These packages provide the 32 bit variants of libgcc, libc as well as the crt object files.

**Comment by ckirsch** [comment]
That's great! I can now generate 32-bit binaries. But running these binaries in lldb does not work. We should discuss how to clean up our toolchain.

**Comment by ckirsch** [comment]
@Blazefrost @fischer-martin @ChristianMoesl I cleaned up the Dockerselfie file a bit, and isolated the packages needed for the machine folder. Could you please clean those up (only have the tools in there that are really needed)?

**Comment by ckirsch** [comment]
After that it may be easier to figure out how to include a 32-bit and 64-bit toolchain.

**Comment by Blazefrost** [comment]
@fischer-martin Do you think we could slim down the requirements for the machine build? Openocd may be optional as it is required for HiFive Unleashed debugging  _only_.

**Comment by fischer-martin** [comment]
> @fischer-martin Do you think we could slim down the requirements for the machine build? Openocd may be optional as it is required for HiFive Unleashed debugging _only_.

Yes, I think it'd be better to throw it out since it only has a very specific use-case for an already very specific part of selfie. Debugging the machine build by hooking into QEMU should suffice.

**Comment by ckirsch** [comment]
Simplifying the dockerselfie image is always good. I worked on it quite a bit, see the #arch branch. Please focus on that version. By now, I can actually develop 32-bit selfie and make progress there. I already found some interesting overflow issues and was able to improve the code.
