### ISSUE TITLE
`self-assembler` assignment results in timeout

### ISSUE THREAD

**Issue by fischer-martin** [cksystemsteaching/selfie#229]
It has been reported to me that the the [current test](https://github.com/cksystemsteaching/selfie/blob/master/grader/self.py#L212) for the `self-assembler` assignment causes a timeout (runtime of 3-5min vs. an allowed maximum of 60s). Since increasing the timeout isn't practical (especially since the bulk-grader doesn't run in parallel), I suggest that we change the test a little bit.

**Comment by fischer-martin** [comment]
Thoughts about that, @ckirsch @Blazefrost ?

**Comment by ckirsch** [comment]
How would you change the test?

**Comment by fischer-martin** [comment]
Maybe compile selfie once from the C* source and assemble it from the output generated by `-s` and then compare the resulting binaries.

**Comment by ckirsch** [comment]
I thought that is what self-assembler checks...what does it actually check?

**Comment by fischer-martin** [comment]
See for yourself:

```def check_self_assemblation() -> List[Check]:
    return check_execution('./selfie -c selfie.c -s selfie1.s -a selfie1.s -m 128 -a selfie1.s -s selfie2.s ',
                           'selfie can assemble its own binary file') + \
        check_execution('diff -q selfie1.s selfie2.s',
                        'both assembly files are exactly the same')```

**Comment by Blazefrost** [comment]
It seems like both assembling and disassembling takes significantly longer on mipster than just compilation.
Maybe we could:
1. Compile, disassemble, assemble, and store a selfie binary
2. Load the binary into a mipster instance and let it compile and store a selfie binary.
3. Compare the resulting binaries from step 1 and 2

If the assemble step is working correctly, the binary from step 1 should be logically equivalent to the host's selfie and produce the same binary in step 2.

**Comment by ckirsch** [comment]
@Blazefrost Sounds good! Please do a PR.
