### ISSUE TITLE
Grader: Replace `threads` task `shared-heap` with thread-safe task

### ISSUE THREAD

**Issue by Blazefrost** [cksystemsteaching/selfie#246]
Like @ckirsch pointed out, task `shared-heap` of assignment `threads` performs a `malloc()` call after creating a thread:
https://github.com/cksystemsteaching/selfie/blob/9b97426301c22228a903057b670c9f70bb885c6c/grader/assignments/threads/shared-heap.c#L20

Unfortunately, `malloc()` is not thread-safe and will probably be impacted by a race condition, depending on `TIMESLICE`.

The task must either be fixed or replaced with a better task.

**Comment by Blazefrost** [comment]
After second thought, I think it should be fine. The main thread creates a second one, but immediately joins with it:
https://github.com/cksystemsteaching/selfie/blob/9b97426301c22228a903057b670c9f70bb885c6c/grader/assignments/threads/shared-heap.c#L17-L19

Only the second thread will call `malloc`, assign a value to the allocated memory, and exit:
https://github.com/cksystemsteaching/selfie/blob/9b97426301c22228a903057b670c9f70bb885c6c/grader/assignments/threads/shared-heap.c#L19-L23

However, I'm open for recommendations of new tasks. I thought about creating a test whether the stacks are properly separated using some conditional nested function calls, depending on the thread ID, but the procedure prologue of the syscalls probably has this case covered already, otherwise the code to check would have a problem with the return address.

**Comment by ckirsch** [comment]
@Blazefrost True. Stack separation should be covered. How about testing the shared data segment as well? If you like you could also implement Dekker's algorithm to see if that works (no atomics required).

**Comment by Blazefrost** [comment]
There's already the [shared-data.c](https://github.com/cksystemsteaching/selfie/blob/9b97426301c22228a903057b670c9f70bb885c6c/grader/assignments/threads/shared-data.c) check for the shared data section.

I've now implemented a check that sums up all integers from 1 to 20 and used Dekker's algorithm for the critical section. This additional check is able to check shared data/heap sections (due to the sum variable and Dekker's algorithm control variables) as well as distinct stacks (due to calls to enter/leave critical sections) in PR #247.

**Comment by ckirsch** [comment]
@Blazefrost Awesome! Thanks a lot.
