### ISSUE TITLE
Compiler warnings with GCC 11.1.0

### ISSUE THREAD

**Issue by Blazefrost** [cksystemsteaching/selfie#286]
When compiling Selfie on the `main` branch, GCC version 11.1.0, [which has been released on April 27th, 2021](https://gcc.gnu.org/pipermail/gcc/2021-April/235922.html), now emits four `-Warray-bounds` warnings.

```
➜  selfie git:(main) ✗ make
cc -Wall -Wextra -O3 -m64 -D'uint64_t=unsigned long long' selfie.c -o selfie
selfie.c: In function ‘string_copy.constprop’:
selfie.c:2518:10: warning: array subscript ‘long long unsigned int[0]’ is partly outside array bounds of ‘char[5]’ [-Warray-bounds]
 2518 |   return get_bits(*((uint64_t*) s + a), (i % SIZEOFUINT64) * 8, 8);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
selfie.c:2518:10: warning: array subscript ‘long long unsigned int[0]’ is partly outside array bounds of ‘char[5]’ [-Warray-bounds]
 2518 |   return get_bits(*((uint64_t*) s + a), (i % SIZEOFUINT64) * 8, 8);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
selfie.c: In function ‘string_copy.constprop’:
selfie.c:2518:10: warning: array subscript ‘long long unsigned int[0]’ is partly outside array bounds of ‘char[6]’ [-Warray-bounds]
 2518 |   return get_bits(*((uint64_t*) s + a), (i % SIZEOFUINT64) * 8, 8);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
selfie.c:2518:10: warning: array subscript ‘long long unsigned int[0]’ is partly outside array bounds of ‘char[6]’ [-Warray-bounds]
 2518 |   return get_bits(*((uint64_t*) s + a), (i % SIZEOFUINT64) * 8, 8);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
➜  selfie git:(main) ✗ gcc --version
gcc (GCC) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

This is problematic since the grader expects Selfie to compile without any warnings.

**Comment by ckirsch** [comment]
@Blazefrost I am surprised it only warns there. Do you have any idea how to avoid that warning?

**Comment by Blazefrost** [comment]
GCC seems to apply an optimization, as indicated by the [`.constprop` function suffix](https://stackoverflow.com/a/14796736). I don't know whether an older GCC version already performed this optimization, but I assume the GCC team either improved the optimizer or the analyzer, or both.

The function `string_copy` is called five times:
* https://github.com/cksystemsteaching/selfie/blob/cfb66194d2de83068faf745248e389a4870d3c74/selfie.c#L5599
* https://github.com/cksystemsteaching/selfie/blob/cfb66194d2de83068faf745248e389a4870d3c74/selfie.c#L5637
* https://github.com/cksystemsteaching/selfie/blob/cfb66194d2de83068faf745248e389a4870d3c74/selfie.c#L5719
* https://github.com/cksystemsteaching/selfie/blob/cfb66194d2de83068faf745248e389a4870d3c74/selfie.c#L7258
* https://github.com/cksystemsteaching/selfie/blob/cfb66194d2de83068faf745248e389a4870d3c74/selfie.c#L7263

So the function is only called with `"main"` and `"_bump"` strings which seems to match with the error messages (`char[5]` and `char[6]`, including the string terminator), and indeed, the function referenced by the warning messages,`load_character`, casts and dereferences these strings as `uint64_t`, even though the memory the pointer points to is smaller than an `uint64_t`.

An easy workaround for now would be to just disable the warning using `-Wno-array-bounds`

**Comment by ckirsch** [comment]
@Blazefrost I just committed a fix: https://github.com/cksystemsteaching/selfie/compare/6c31681f7c05...fb7c25457840 Could you please check if that avoids the warnings?

**Comment by Blazefrost** [comment]
Yes, commit `fb7c254` fixed the warnings for me. :+1:
