### ISSUE TITLE
Residual files in selfie root directory in the selfie docker image after machine build

### ISSUE THREAD

**Issue by ckirsch** [cksystemsteaching/selfie#287]
@Blazefrost could you please help me in fixing the following issue:

The selfie root directory in the selfie docker image contains two residual files called `hello-world.m` and `selfie.m` which, I believe, are created during `RUN make --directory machine/`. I think it would be better if those two files are removed somehow or put in the `machine` folder.

What do you think?

**Comment by Blazefrost** [comment]
I*ve created a pull request that puts the RISC-U binaries in machine`s `build` directory so that the repository root is not populated with machine artifacts. As `make --directory machine clean` removes the build directory, it will remove the binaries now as well .
