### ISSUE TITLE
Compiling under Windows?

### ISSUE THREAD

**Issue by nubok** [cksystemsteaching/selfie#29]
In README.md one can read:

> Selfie runs on Mac, Linux, Windows and possibly other systems that have a terminal and a C compiler installed.

On the other hand only instructions for compiling (and running) Selfie under UNIX-like operating systems are given. So what is the designated way to compile Selfie under Windows using Visual C++ using either cmd.exe (e.g. via "x86 Native Tools Command Prompt"; though Microsoft considers this terminal as deprecated) or PowerShell?

**Comment by ChristianMoesl** [comment]
On Windows we usually use a Linix environment like msys2 and gcc or clang as compiler. For the Visual C++ compiler and PowerShell, you need to install make and modify the [Makefile](https://github.com/cksystemsteaching/selfie/blob/master/Makefile) to match the [available compiler options](https://msdn.microsoft.com/en-us/library/fwkeyyhe.aspx).

**Comment by nubok** [comment]
So I will work on writing a Makefile for Windows that can be used with nmake.

**Comment by nubok** [comment]
As promised I created a pull request that might not be perfect, but at least allows selfie to compile using Visual Studio 2017/nmake: https://github.com/cksystemsteaching/selfie/pull/31

Note that one (two?) of the tests currently fail under this configuration. I am not in the position to be able to find the reason for this test failure.

**Comment by ChristianMoesl** [comment]
Great! I'm working on this Problem already. It has something to do with the hypster starting on boot level zero. 

If your are interested in it, PR #32  fixes this bug on Windows ([commit](https://github.com/cksystemsteaching/selfie/pull/32/commits/93e93305a26341af8f3c9191a7b7826f73f1f06e)).

**Comment by nubok** [comment]
> If your are interested in it, PR #32 fixes this bug on Windows (commit).

For testing I merged the ChristianMoesl:vpage-size branch with my Makefile.win changes. To make this result reproducable I created a new patch "vpage_win" for this experiment and uploaded it:

> https://github.com/nubok/selfie/tree/vpage_win

The results are "interesting":

`> selfie.exe -c selfie.c -o selfie3.m -s selfie3.s -y 3 -l selfie3.m -y 2 -l selfie3.m -y 2 -c selfie.c -o selfie4.m -s selfie4.s`

now works:

```
.\selfie.exe: this is selfie compiling selfie.c with starc
.\selfie.exe: 203502 characters read in 7736 lines and 1053 comments
.\selfie.exe: with 108028(53.19%) characters in 31818 actual symbols
.\selfie.exe: 272 global variables, 313 procedures, 456 string literals
.\selfie.exe: 2139 calls, 827 assignments, 71 while, 646 if, 293 return
.\selfie.exe: 132464 bytes generated with 31435 instructions and 6724 bytes of data
.\selfie.exe: 132464 bytes with 31435 instructions and 6724 bytes of data written into selfie3.m
.\selfie.exe: 1322223 characters of assembly with 31435 instructions written into selfie3.s
.\selfie.exe: this is selfie executing selfie3.m with 3MB of physical memory on mipster
selfie3.m: 132464 bytes with 31435 instructions and 6724 bytes of data loaded from selfie3.m
selfie3.m: this is selfie executing selfie3.m with 2MB of physical memory on hypster
selfie3.m: 132464 bytes with 31435 instructions and 6724 bytes of data loaded from selfie3.m
selfie3.m: this is selfie executing selfie3.m with 2MB of physical memory on hypster
selfie3.m: this is selfie compiling selfie.c with starc
selfie3.m: 203502 characters read in 7736 lines and 1053 comments
selfie3.m: with 108028(53.19%) characters in 31818 actual symbols
selfie3.m: 272 global variables, 313 procedures, 456 string literals
selfie3.m: 2139 calls, 827 assignments, 71 while, 646 if, 293 return
selfie3.m: 132464 bytes generated with 31435 instructions and 6724 bytes of data
selfie3.m: 132464 bytes with 31435 instructions and 6724 bytes of data written into selfie4.m
selfie3.m: 1322223 characters of assembly with 31435 instructions written into selfie4.s
selfie3.m: selfie3.m exiting with exit code 0 and 1.39MB of mallocated memory
selfie3.m: this is selfie terminating selfie3.m with exit code 0 and 1.27MB of mapped memory
selfie3.m: selfie3.m exiting with exit code 0 and 7.25MB of mallocated memory
selfie3.m: this is selfie terminating selfie3.m with exit code 0 and 1.66MB of mapped memory
.\selfie.exe: selfie3.m exiting with exit code 0 and 7.25MB of mallocated memory                                        .\selfie.exe: this is selfie terminating selfie3.m with exit code 0 and 2.06MB of mapped memory
.\selfie.exe: profile: total,max(ratio%)@addr(line#),2max(ratio%)@addr(line#),3max(ratio%)@addr(line#)                  .\selfie.exe: calls: 215690295,65211073(30.30%)@0x3278(~1443),31959586(14.83%)@0x3638(~1486),18694311(8.67%)@0x32D8(~1449)                                                                                                                      .\selfie.exe: loops: 12426596,3102138(25.00%)@0x1C09C(~7117),2712207(21.83%)@0x129C8(~5120),2633418(21.23%)@0x77FC(~2478)                                                                                                                       .\selfie.exe: loads: 1644702509,65211073(3.96%)@0x328C(~1443),31959586(1.94%)@0x364C(~1486),31950754(1.94%)@0x36A4(~1489)
.\selfie.exe: stores: 936609332,65211073(6.96%)@0x327C(~1443),31959586(3.41%)@0x363C(~1486),31904127(3.40%)@0x36D8(~1491)
```

But on the other hand 

`> selfie.exe -c selfie.c -o selfie5.m -s selfie5.s -min 4 -l selfie5.m -y 2 -l selfie5.m -y 2 -c selfie.c -o selfie6.m -s selfie6.s`

will now fail:

```
.\selfie.exe: this is selfie compiling selfie.c with starc
.\selfie.exe: 203502 characters read in 7736 lines and 1053 comments
.\selfie.exe: with 108028(53.19%) characters in 31818 actual symbols
.\selfie.exe: 272 global variables, 313 procedures, 456 string literals
.\selfie.exe: 2139 calls, 827 assignments, 71 while, 646 if, 293 return
.\selfie.exe: 132464 bytes generated with 31435 instructions and 6724 bytes of data
.\selfie.exe: 132464 bytes with 31435 instructions and 6724 bytes of data written into selfie5.m
.\selfie.exe: 1322223 characters of assembly with 31435 instructions written into selfie5.s
.\selfie.exe: this is selfie executing selfie5.m with 4MB of physical memory on minster
selfie5.m: 132464 bytes with 31435 instructions and 6724 bytes of data loaded from selfie5.m
.\selfie.exe: context selfie5.m throws uncaught page fault at 0x00000581
.\selfie.exe: this is selfie terminating selfie5.m with exit code -8 and 4.00MB of mapped memory
.\selfie.exe: profile: total,max(ratio%)@addr(line#),2max(ratio%)@addr(line#),3max(ratio%)@addr(line#)
.\selfie.exe: calls: 3048,1309(43.10%)@0x3278(~1443),659(21.64%)@0x3638(~1486),399(13.10%)@0x32D8(~1449)
.\selfie.exe: loops: 238,92(38.75%)@0x4F90(~1855),63(26.52%)@0x1140C(~4825),30(12.61%)@0x1AC(~230)
.\selfie.exe: loads: 25040,1309(5.23%)@0x328C(~1443),659(2.63%)@0x364C(~1486),399(1.59%)@0x32F0(~1449)
.\selfie.exe: stores: 13835,1309(9.46%)@0x327C(~1443),659(4.76%)@0x363C(~1486),399(2.88%)@0x32DC(~1449)
NMAKE : fatal error U1077: '.\selfie.exe' : return code '0xfffffff8'
```

**Comment by ChristianMoesl** [comment]
I changed the Makefile in my PR! The command should look like
 `./selfie -c selfie.c -o selfie5.m -s selfie5.s -min 8 -l selfie5.m -y 2 -l selfie5.m -y 2 -c selfie.c -o selfie6.m -s selfie6.s`
This is needed because the page table size in selfie increased dramatically.

**Comment by nubok** [comment]
I tried it out: This change indeed fixes the problem.  In other words: After this patch `nmake -f Makefile.win all` ran all through without any abnormalities visible to me. So I merged this into "my" vpage-win branch:

> https://github.com/nubok/selfie/commit/e1a67ab479207ef3f21b997677586889cecb0156

**Comment by ChristianMoesl** [comment]
We will stay with the the combination of a Unix subsystem (msys2/cygwin) with gcc/clang as toolchain for windows users.
