### ISSUE TITLE
Naming the programming language C* causes some confusion

### ISSUE THREAD

**Issue by pjmlp** [cksystemsteaching/selfie#349]
As it is the name of the C dialect used in the [Connection Machine](https://en.wikipedia.org/wiki/Connection_Machine).

[https://en.wikipedia.org/wiki/C*](https://en.wikipedia.org/wiki/C*)

**Comment by ckirsch** [comment]
Interesting! Didn't know about that. Well, too late now. Changing the name would take all my time and cause even more confusion. But thank you for pointing this out!
