### ISSUE TITLE
Rotor disassembly produces incorrect immediate values for certain instructions

### ISSUE THREAD

**Issue by Jean-M22** [cksystemsteaching/selfie#382]
### Steps to reproduce

<details>
<summary>Click to expand</summary>

1. Build a source file (I'm using `examples/symbolic/division-by-zero-3-35.c`)
```
riscv64-unknown-elf-gcc -Wall -Wextra -D'uint64_t=unsigned long' examples/symbolic/division-by-zero-3-35.c -o test
```
2. Run riscv objdump on the binary
```
riscv64-unknown-elf-objdump -d test
```
3. Run rotor disassembly on the binary
```
./rotor -l test - 0 -s
```
4. Compare the outputs

---

Alternatively,
1. Build a source file (I'm using `examples/symbolic/division-by-zero-3-35.c`)
```
riscv64-unknown-elf-gcc -Wall -Wextra -D'uint64_t=unsigned long' examples/symbolic/division-by-zero-3-35.c -o test
```
2. Checkout the pull request brach for #380
```
git fetch origin pull/380/head:objdump-compare
```
3. Switch to the new branch
```
git switch objdump-compare
```
4. Run the python tool to compare outputs
```
python3 tools/objdump_analyzer.py test
```

</details>

### Expected results

Rotor should output the same immediate values as riscv objdump (which is usually the case but not always.)

### Actual results

Certain instructions (including, but potentially not limited to `lui`, `andi` and `auipc`) have immediate values which differ from the ones given by riscv objdump

#### Observed discrepancies:
1. Rotor value is `?000` where ? is the riscv objdump value (multiplied by 4096)
_(only happened with `lui` and `auipc` for me)_
![image](https://github.com/cksystemsteaching/selfie/assets/38384519/1698ce2c-8a6f-4e95-9d07-412832acb907)
![image](https://github.com/cksystemsteaching/selfie/assets/38384519/5437ecc5-2dfa-4423-be21-286248142e45)

2. Rotor value is `FFFFFFFF?000` where ? is the riscv objdump value
_(only happened with `lui` for me)_
![image](https://github.com/cksystemsteaching/selfie/assets/38384519/df46d6cf-2d8d-46c0-a26d-65b974667cd8)
![image](https://github.com/cksystemsteaching/selfie/assets/38384519/97b1d34b-feed-40bc-8eac-5b2a7d101d11)

3. Rotor value is simply wrong (cannot find a pattern)
_(only happened with `andi` for me)_
![image](https://github.com/cksystemsteaching/selfie/assets/38384519/1e3713ef-8d9b-40f8-b518-04126840e570)
![image](https://github.com/cksystemsteaching/selfie/assets/38384519/85936705-d0bf-402c-a51e-1f52b19a78be)
![image](https://github.com/cksystemsteaching/selfie/assets/38384519/92339608-04b5-4d87-a91b-41209dff918c)

---

This might be outside the scope of this issue, but there's also the problem that rotor doesn't output negative numbers, so this happens
![image](https://github.com/cksystemsteaching/selfie/assets/38384519/78d469d0-26e3-4d88-9d3a-49114d3775c8)

**Comment by ckirsch** [comment]
@Jean-M22 I just committed potential fixes to all of the above. Please check and see if this introduces new bugs. Many thanks!
