### ISSUE TITLE
encoding glitch

### ISSUE THREAD

**Issue by cponcelets** [cksystemsteaching/selfie#41]
In selfie/manuscript/semantics.md.
The symbol -- appears like â€”. However, it is not a markdown error.

[Disassembler](https://en.wikipedia.org/wiki/Disassembler)
: A computer program that translates machine language into assembly language -- the inverse operation to that of an assembler.

**Comment by cponcelets** [comment]
Idem in selfie/manuscript/state.md.

A programming paradigm â€” a style of building the structure and elements of computer programs â€” that expresses the logic of a computation without describing its control flow.

**Comment by ckirsch** [comment]
Thanks, @cponcelets I just fixed this.
