### ISSUE TITLE
Division with integer literals gives wrong result

### ISSUE THREAD

**Issue by ChristianMoesl** [cksystemsteaching/selfie#45]
The following c snippet gives different results on selfie compared to gcc/clang
`
uint64_t a;
a = (-1) / 2;
`

With selfie we get for a: `9223372036854775807`
With gcc we get for a: `0`

This is due to the lack of integer division in Selfie.

**Comment by ChristianMoesl** [comment]
Should we forbid this specific case?

**Comment by alexkollert** [comment]
In the branch elf I had to handle theses cases like you suggest, so that selfie can be executed on the qemu emulator. Negative Operands are first converted to positive before Division and converted back to negative after division. But this seemed to cause issues with clang vs. gcc. Still investigating that issue

**Comment by ckirsch** [comment]
@christianmoesl I am not sure why this happens. We do use `/` for implementing the DIVU instruction and thus for implementing `/` in turn, right?

**Comment by ChristianMoesl** [comment]
@ckirsch A integer literal in C `-1` or `1` has a signed integer type. Therefore signed division is used when calculating with literals, before they were casted to a `uint64_t` type (because of the assignment).
In Selfie every integer literal gets immediately "converted" into a a `uint64_t` type and afterwards calculated.

**Comment by ckirsch** [comment]
Interesting! Please create a file`semantics.md` on root level for gathering all cases of C* semantics that are different from C semantics. This one should be the first but there is probably more.
