### ISSUE TITLE
disassembling issue

### ISSUE THREAD

**Issue by aabyaneh** [cksystemsteaching/selfie#57]
@ChristianMoesl By execution of these two consecutive command lines
`./selfie -c selfie.c -o selfie.m`
`./selfie -l selfie.m -s selfie.s`
`selfie.s` will contain "./selfie: unknown instruction with 101101 opcode detected" at the last line.

The reason should be because of this line `codeLength = *(ELF_header + 12);` in `selfie_load()` which stores the size of the binary (including data segment) into `codeLength`. So, the wrong value of `codeLength` will be used in `selfie_disassembler()` function.

**Comment by ckirsch** [comment]
@ChristianMoesl @alexkollert Please look into this. We need a robust way of dealing with the non-zero offset of code in memory etc. Thanks!

**Comment by alexkollert** [comment]
in the moment the ELF Header does not distinguish between code and data. This could be resolved either by adding a second program header or by a bunch of section headers.

**Comment by ChristianMoesl** [comment]
This issue should be resolved with #59 . I added the code length as separate parameter into the binary file, so that i don't have to use the binary length as code length.
